# Generated by Django 4.2.1 on 2024-07-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='forget_password_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
